[tools]
opam = "latest"
ruby = "latest"
gleam = "latest"
python = "latest"
awscli = "latest"
java = "openjdk"
dotnet = "latest"
erlang = "latest"
node = "latest"
bun = "latest"
deno = "latest"
go = "latest"
zig = "latest"
pnpm = "latest"
yarn = "latest"
atlas = "0.36"
biome = "latest"
odin = "dev-2025-11"
"go:github.com/air-verse/air" = "latest"
"go:github.com/golang-migrate/migrate/v4/cmd/migrate" = { version = "latest", tags = "postgres mysql sqlite3" }
"go:github.com/pressly/goose/v3/cmd/goose" = "latest"
"go:github.com/fzipp/gocyclo/cmd/gocyclo" = "latest"
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "latest"
"go:github.com/fatih/gomodifytags" = "latest"
"go:github.com/securego/gosec/v2/cmd/gosec" = "latest"
"go:go.uber.org/mock/mockgen" = "latest"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"
"go:github.com/a-h/templ/cmd/templ" = "latest"

[settings]
experimental = true

